using Microsoft.AspNetCore.Mvc;
using Arasan.Interface;
using Arasan.Interface.Report;
using Arasan.Models;
using Arasan.Services;
using Arasan.Services.Report;
//using DocumentFormat.OpenXml.Office2010.Excel;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using ClosedXML.Excel;
using System.Data.SqlClient;
using Oracle.ManagedDataAccess.Client;
using Microsoft.CodeAnalysis.Operations;
using Intuit.Ipp.DataService;

namespace Arasan.Controllers
{
    public class CuringShedStockPolishController : Controller
    {
        ICuringShedStockPolish CuringShedStockPolishService;
        IConfiguration? _configuratio;
        private string? _connectionString;

        DataTransactions datatrans;
        private object excelData;

        public CuringShedStockPolishController(ICuringShedStockPolish _CuringShedStockPolishService, IConfiguration _configuratio)
        {
            CuringShedStockPolishService = _CuringShedStockPolishService;
            _connectionString = _configuratio.GetConnectionString("OracleDBConnection");
            datatrans = new DataTransactions(_connectionString);
        }
        public IActionResult CuringShedStockPolish(string strfrom, string strTo)
        {

            try
            {
                CuringShedStockPolishModel objR = new CuringShedStockPolishModel();

                objR.dtFrom = strfrom;
                objR.dtTo = strTo;
                return View(objR);
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }
        public ActionResult MyListPurchaseRepItemReportGrid(string dtFrom, string dtTo)
        {
            List<CuringShedStockPolishModelItem> Reg = new List<CuringShedStockPolishModelItem>();
            DataTable dtUsers = new DataTable();

            dtUsers = (DataTable)CuringShedStockPolishService.GetAllCuringShedStockPolish(dtFrom, dtTo);
            for (int i = 0; i < dtUsers.Rows.Count; i++)
            {


                Reg.Add(new CuringShedStockPolishModelItem
                {
                    docdate = dtUsers.Rows[i]["DOCDATE"].ToString(),
                    opqty = dtUsers.Rows[i]["OPQTY"].ToString(),
                    rqty = dtUsers.Rows[i]["RQTY"].ToString(),
                    ipkqty = dtUsers.Rows[i]["IPKQTY"].ToString(),
                    impkqty = dtUsers.Rows[i]["IMPKQTY"].ToString(),
                    ipoqty = dtUsers.Rows[i]["IPOQTY"].ToString(),
                    ipyqty = dtUsers.Rows[i]["IPYQTY"].ToString(),
                    ipaqty = dtUsers.Rows[i]["IPAQTY"].ToString(),
                    stkpqty = dtUsers.Rows[i]["STKPQTY"].ToString(),
                    stkmqty = dtUsers.Rows[i]["STKMQTY"].ToString(),
                    fdrm = dtUsers.Rows[i]["FDRM"].ToString(),
                    itemqty = dtUsers.Rows[i]["ITEMQTY"].ToString(),
                    pack = dtUsers.Rows[i]["PACK"].ToString(),
                    drum = dtUsers.Rows[i]["DRUM"].ToString(),
                    str = dtUsers.Rows[i]["STR"].ToString(),


                });
            }

            return Json(new
            {
                Reg
            });

        }




        public IActionResult ExportToExcel(string dtFrom, string dtTo)
        {
            DataTransactions _datatransactions;
            DataTable dtNew1 = new DataTable();

            string SvSql = "";

            //SvSql = "SELECT X.DOCDATE , SUM(X.OPQTY) OQ , SUM(X.RQTY) RQ,Sum(Str) Str , SUM(X.IPKQTY) IPKQ, SUM(X.IMPKQTY) IMPKQ , SUM(X.IPOQTY) IPOQ , SUM(X.IPYQTY) IPYQ, SUM(X.IPAQTY) IPAQ,\r\nSUM(STKPQTY) STKPQTY,SUM(STKMQTY) STKMQTY,SUM(FDRM) FDRM,SUM(ITEMQTY) ITEMQTY,SUM(PACK) PACK,SUM(DRUM) DRUM,SUm(ITEMCQTY) ITEMCQTY\r\nFROM \r\n(\r\nSELECT '" + dtFrom + "' DOCDATE , SUM(QTY) OPQTY , 0 RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY , 0 IPYQTY,0 IPAQTY,0 STKPQTY,0 STKMQTY,\r\n 0 FDRM,0 ITEMQTY,0 PACK,0 DRUM,0 STR,0 ITEMCQTY\r\nFROM\r\n(\r\nSELECT TL.LOCID , I.ITEMID , LS.DRUMNO , SUM(LS.PLUSQTY-LS.MINUSQTY) QTY\r\nFROM LSTOCKVALUE LS , LOCDETAILS TL , ITEMMASTER I\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND (  TL.LOCID IN ('CURING' , 'RVD SHED') OR TL.LOCATIONTYPE IN ('PACKING','POLISH' ))\r\nAND I.SNCATEGORY IN ('POLISH POWDER')\r\nAND LS.DRUMNO IS NOT NULL\r\nAND LS.DOCDATE < '" + dtFrom + "'\r\nGROUP BY TL.LOCID ,  I.ITEMID , LS.DRUMNO\r\nHAVING SUM(LS.PLUSQTY-LS.MINUSQTY)  > 0\r\n)\r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY ,SUM(LS.PLUSQTY) RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY , 0 IPYQTY, 0 IPAQTY,0 STKPQTY,0 STKMQTY,\r\n 0 FDRM,0 ITEMQTY,0 PACK,0 DRUM,0 STR,0\r\nFROM LSTOCKVALUE LS , LOCDETAILS TL , ITEMMASTER I\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND (  TL.LOCID IN ('CURING' , 'RVD SHED') OR TL.LOCATIONTYPE IN ( 'POLISH','PACKING') )\r\nAND I.SNCATEGORY IN ('POLISH POWDER')\r\nAND LS.DRUMNO IS NOT NULL\r\nAND LS.DOCDATE BETWEEN  '" + dtFrom + "' AND '" + dtTo + "'\r\nAND LS.STOCKTRANSTYPE= 'PACKING ISSUE'\r\nGROUP BY TL.LOCID,LS.DOCDATE\r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY , SUM(LS.PLUSQTY) RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY , 0 IPYQTY,0 IPAQTY, 0 STKPQTY,0 STKMQTY, \r\n0 FDRM,0 ITEMQTY,0 PACK,0 DRUM,0 STR,0\r\nFROM LSTOCKVALUE LS , ITEMMASTER I , LOCDETAILS TL\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND I.SNCATEGORY IN ('POLISH POWDER')\r\nAND (TL.LOCID IN ( 'CURING' , 'RVD SHED' ) OR TL.LOCATIONTYPE IN ( 'POLISH') )\r\nAND LS.DOCDATE BETWEEN '" + dtFrom + "' AND '" + dtTo + "'\r\nAND LS.STOCKTRANSTYPE = 'BPROD OUTPUT'\r\nGROUP BY TL.LOCID , LS.DOCDATE\r\nUNION ALL\r\nselect s.DOCDATE , 0 OPQTY , sum(s.PLUSQTY) RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY , 0 IPYQTY, 0 IPAQTY, 0 STKPQTY,0 STKMQTY,0 FDRM,\r\n0 ITEMQTY,0 PACK,0 DRUM,0 STR,0\r\nfrom lstockvalue s ,locdetails l,itemmaster i\r\nwhere s.STOCKTRANSTYPE = 'DIRECT ADDITION'\r\nAND S.DOCDATE BETWEEN  '" + dtFrom + "' AND  '" + dtTo + "'\r\nand s.LOCID = l.LOCDETAILSID\r\nAND (  l.LOCID IN ('CURING' , 'RVD SHED') OR l.LOCATIONTYPE IN ( 'POLISH','PACKING') )\r\nand s.ITEMID = i.ITEMMASTERID\r\nand i.SNCATEGORY = 'POLISH POWDER'\r\ngroup by s.DOCDATE\r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY , 0 RQTY , SUM(LS.MINUSQTY) IPKQTY,0 , 0 IPOQTY , 0 IPYQTY, 0 IPAQTY, 0 STKPQTY,0 STKMQTY, \r\n0 FDRM,0 ITEMQTY,0 PACK,0 DRUM,0 STR,0\r\nFROM LSTOCKVALUE LS,ITEMMASTER I, LOCDETAILS TL \r\nWHERE I.ITEMMASTERID = LS.ITEMID\r\nAND  I.SNCATEGORY IN ('POLISH POWDER')\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nand TL.LOCATIONTYPE='PACKING'\r\nAND LS.DOCDATE BETWEEN '" + dtFrom + "' AND '" + dtTo + "'\r\nAND LS.STOCKTRANSTYPE = 'PACKING INPUT'\r\nGROUP BY TL.LOCID ,  LS.DOCDATE \r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY , 0 RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY , SUM(LS.PLUSQTY) IPYQTY, 0 IPAQTY,0 STKPQTY,0 STKMQTY, \r\n0 FDRM,0 ITEMQTY,0 PACK,0 DRUM,0 STR,0\r\nFROM LSTOCKVALUE LS , ITEMMASTER I , LOCDETAILS TL , LOCDETAILS FL\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND I.SNCATEGORY IN ('POLISH POWDER')\r\nAND TL.LOCATIONTYPE= 'BALL MILL'\r\nAND LS.FROMLOCID = FL.LOCDETAILSID\r\nAND FL.LOCATIONTYPE IN ('CURING','POLISH','PACKING')\r\nAND LS.DOCDATE BETWEEN '" + dtFrom + "' AND '" + dtTo + "'\r\nAND LS.STOCKTRANSTYPE IN ('CURING RECHARGE','DRUM ISSUE')\r\nGROUP BY TL.LOCID , FL.LOCID , LS.DOCDATE\r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY , 0 RQTY , 0 IPKQTY,0 , SUM(LS.MINUSQTY) IPOQTY , 0 IPYQTY,0 IPAQTY, 0 STKPQTY,0 STKMQTY, \r\n0 FDRM,0 ITEMQTY,0 PACK,0 DRUM,0 STR,0\r\nFROM LSTOCKVALUE LS , ITEMMASTER I , LOCDETAILS TL\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND I.SNCATEGORY IN ('POLISH POWDER')\r\nAND TL.LOCATIONTYPE = 'POLISH'\r\nAND LS.DOCDATE BETWEEN '" + dtFrom + "' AND '" + dtTo + "'\r\nAND LS.STOCKTRANSTYPE = 'BPROD INPUT'\r\nGROUP BY TL.LOCATIONTYPE , LS.DOCDATE\r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY , 0 RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY , 0 IPYQTY,0 IPAQTY, 0 STKPQTY,SUM(MINUSQTY) STKMQTY, \r\n0 FDRM,0 ITEMQTY,0 PACK,0 DRUM,0 STR,0\r\nFROM LSTOCKVALUE LS , LOCDETAILS TL , ITEMMASTER I\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND (TL.LOCID IN ( 'CURING' , 'RVD SHED' ) OR TL.LOCATIONTYPE IN ( 'POLISH','PACKING') )\r\nAND I.SNCATEGORY IN ('POLISH POWDER')\r\nAND LS.DRUMNO IS NOT NULL\r\nAND LS.DOCDATE BETWEEN  '" + dtFrom + "' AND  '" + dtTo + "'\r\nAND UPPER(LS.STOCKTRANSTYPE) in  ('STOCK RECONCILATION','STOCK VARIATION','FIRE DRUMS','DIRECT DEDUCTION','DRUM STK RECL')\r\nGROUP BY TL.LOCATIONTYPE,LS.DOCDATE\r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY , 0 RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY ,0 IPYQTY, SUM(LS.PLUSQTY) IPAQTY,0 STKPQTY,0 STKMQTY, \r\n0 FDRM,0 ITEMQTY,0 PACK,0 DRUM,0 STR,0\r\nFROM LSTOCKVALUE LS , ITEMMASTER I , LOCDETAILS TL , LOCDETAILS FL\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND I.SNCATEGORY IN ('POLISH POWDER')\r\nAND TL.LOCATIONTYPE='PASTE'\r\nAND LS.FROMLOCID = FL.LOCDETAILSID\r\nAND FL.LOCATIONTYPE IN ('CURING','POLISH','PACKING')\r\nAND LS.DOCDATE BETWEEN '" + dtFrom + "' AND '" + dtTo + "'\r\nAND LS.STOCKTRANSTYPE IN ('CURING RECHARGE','DRUM ISSUE')\r\nGROUP BY TL.LOCID , FL.LOCID , LS.DOCDATE\r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY , 0 RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY , 0 IPYQTY,0 IPAQTY, 0 STKPQTY,0 STKMQTY,0 FDRM,\r\nSUM(LS.PLUSQTY) ITEMQTY,0 PACK,0 DRUM,0 STR,0\r\nFROM LSTOCKVALUE LS , LOCDETAILS TL , ITEMMASTER I, ICEDETAIL ICD, ICEBASIC ICB, ITEMMASTER FI\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND ICB.ICEBASICID = ICD.ICEBASICID\r\nAND ICD.ICEDETAILID = LS.T1SOURCEID\r\nAND ICB.FITEMID = FI.ITEMMASTERID\r\nAND FI.SNCATEGORY <> I.SNCATEGORY\r\nAND (TL.LOCID IN ( 'CURING' , 'RVD SHED' ) OR TL.LOCATIONTYPE IN ( 'POLISH','PACKING') )\r\nAND I.SNCATEGORY = 'POLISH POWDER'\r\nAND LS.DOCDATE BETWEEN '" + dtFrom + "' AND '" + dtTo + "'\r\nAND LS.STOCKTRANSTYPE = 'ITEM CONV' \r\nGROUP BY LS.DOCDATE , TL.LOCID\r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY , 0 RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY , 0 IPYQTY,0 IPAQTY, 0 STKPQTY,0 STKMQTY,0 FDRM,\r\n0  ITEMQTY,0 PACK,0 DRUM,0 STR, SUM(LS.MINUSQTY) ITEMCQTY\r\nFROM LSTOCKVALUE LS , LOCDETAILS TL , ITEMMASTER I, ICEDETAIL ICD, ICEBASIC ICB, ITEMMASTER FI\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND ICB.ICEBASICID = ICD.ICEBASICID\r\nAND ICD.ICEDETAILID = LS.T1SOURCEID\r\nAND ICB.TITEMID = FI.ITEMMASTERID\r\nAND FI.SNCATEGORY <> I.SNCATEGORY\r\nAND (TL.LOCID IN ( 'CURING' , 'RVD SHED' ) OR TL.LOCATIONTYPE IN ( 'POLISH','PACKING') )\r\nAND I.SNCATEGORY = 'POLISH POWDER'\r\nAND LS.DOCDATE BETWEEN '" + dtFrom + "' AND '" + dtTo + "'\r\nAND LS.STOCKTRANSTYPE = 'ITEM CONV' \r\nGROUP BY LS.DOCDATE , TL.LOCID\r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY , 0 RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY ,0 IPYQTY, 0 IPAQTY,0 STKPQTY,0 STKMQTY, \r\n0 FDRM,0 ITEMQTY,0 PACK,0 DRUM,SUM(LS.PLUSQTY) StR,0\r\nFROM LSTOCKVALUE LS , ITEMMASTER I , LOCDETAILS TL , LOCDETAILS FL\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND I.SNCATEGORY IN ('POLISH POWDER')\r\nAND TL.LOCATIONTYPE='PACKING'\r\nAND LS.FROMLOCID = FL.LOCDETAILSID\r\nAND FL.LOCATIONTYPE IN ('STORES')\r\nAND LS.DOCDATE BETWEEN '" + dtFrom + "' AND '" + dtTo + "'\r\nGROUP BY TL.LOCID , FL.LOCID , LS.DOCDATE\r\n) X\r\nGROUP BY X.DOCDATE\r\nORDER BY X.DOCDATE";
            SvSql = "SELECT LS.DOCDATE , 0 OPQTY ,SUM(LS.PLUSQTY) RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY , 0 IPYQTY, 0 IPAQTY,0 STKPQTY,0 STKMQTY,\r\n 0 FDRM,0 ITEMQTY,0 PACK,0 DRUM,0 STR,0\r\nFROM LSTOCKVALUE LS , LOCDETAILS TL , ITEMMASTER I\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND (  TL.LOCID IN ('CURING' , 'RVD SHED') OR TL.LOCATIONTYPE IN ( 'POLISH','PACKING') )\r\nAND I.SNCATEGORY IN ('POLISH POWDER')\r\nAND LS.DRUMNO IS NOT NULL\r\nAND LS.DOCDATE BETWEEN  '"+dtFrom+"' AND '"+dtTo+"'\r\nAND LS.STOCKTRANSTYPE= 'PACKING ISSUE'\r\nGROUP BY TL.LOCID,LS.DOCDATE\r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY , SUM(LS.PLUSQTY) RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY , 0 IPYQTY,0 IPAQTY, 0 STKPQTY,0 STKMQTY, \r\n0 FDRM,0 ITEMQTY,0 PACK,0 DRUM,0 STR,0\r\nFROM LSTOCKVALUE LS , ITEMMASTER I , LOCDETAILS TL\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND I.SNCATEGORY IN ('POLISH POWDER')\r\nAND (TL.LOCID IN ( 'CURING' , 'RVD SHED' ) OR TL.LOCATIONTYPE IN ( 'POLISH') )\r\nAND LS.DOCDATE BETWEEN '"+dtFrom+"' AND '"+dtTo+"'\r\nAND LS.STOCKTRANSTYPE = 'BPROD OUTPUT'\r\nGROUP BY TL.LOCID , LS.DOCDATE\r\nUNION ALL\r\nselect s.DOCDATE , 0 OPQTY , sum(s.PLUSQTY) RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY , 0 IPYQTY, 0 IPAQTY, 0 STKPQTY,0 STKMQTY,0 FDRM,\r\n0 ITEMQTY,0 PACK,0 DRUM,0 STR,0\r\nfrom lstockvalue s ,locdetails l,itemmaster i\r\nwhere s.STOCKTRANSTYPE = 'DIRECT ADDITION'\r\nAND S.DOCDATE BETWEEN  '"+dtFrom+"' AND  '"+dtTo+"'\r\nand s.LOCID = l.LOCDETAILSID\r\nAND (  l.LOCID IN ('CURING' , 'RVD SHED') OR l.LOCATIONTYPE IN ( 'POLISH','PACKING') )\r\nand s.ITEMID = i.ITEMMASTERID\r\nand i.SNCATEGORY = 'POLISH POWDER'\r\ngroup by s.DOCDATE\r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY , 0 RQTY , SUM(LS.MINUSQTY) IPKQTY,0 , 0 IPOQTY , 0 IPYQTY, 0 IPAQTY, 0 STKPQTY,0 STKMQTY, \r\n0 FDRM,0 ITEMQTY,0 PACK,0 DRUM,0 STR,0\r\nFROM LSTOCKVALUE LS,ITEMMASTER I, LOCDETAILS TL \r\nWHERE I.ITEMMASTERID = LS.ITEMID\r\nAND  I.SNCATEGORY IN ('POLISH POWDER')\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nand TL.LOCATIONTYPE='PACKING'\r\nAND LS.DOCDATE BETWEEN '"+dtFrom+"' AND '"+dtTo+"'\r\nAND LS.STOCKTRANSTYPE = 'PACKING INPUT'\r\nGROUP BY TL.LOCID ,  LS.DOCDATE \r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY , 0 RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY , SUM(LS.PLUSQTY) IPYQTY, 0 IPAQTY,0 STKPQTY,0 STKMQTY, \r\n0 FDRM,0 ITEMQTY,0 PACK,0 DRUM,0 STR,0\r\nFROM LSTOCKVALUE LS , ITEMMASTER I , LOCDETAILS TL , LOCDETAILS FL\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND I.SNCATEGORY IN ('POLISH POWDER')\r\nAND TL.LOCATIONTYPE= 'BALL MILL'\r\nAND LS.FROMLOCID = FL.LOCDETAILSID\r\nAND FL.LOCATIONTYPE IN ('CURING','POLISH','PACKING')\r\nAND LS.DOCDATE BETWEEN '"+dtFrom+"' AND '"+dtTo+"'\r\nAND LS.STOCKTRANSTYPE IN ('CURING RECHARGE','DRUM ISSUE')\r\nGROUP BY TL.LOCID , FL.LOCID , LS.DOCDATE\r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY , 0 RQTY , 0 IPKQTY,0 , SUM(LS.MINUSQTY) IPOQTY , 0 IPYQTY,0 IPAQTY, 0 STKPQTY,0 STKMQTY, \r\n0 FDRM,0 ITEMQTY,0 PACK,0 DRUM,0 STR,0\r\nFROM LSTOCKVALUE LS , ITEMMASTER I , LOCDETAILS TL\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND I.SNCATEGORY IN ('POLISH POWDER')\r\nAND TL.LOCATIONTYPE = 'POLISH'\r\nAND LS.DOCDATE BETWEEN '"+dtFrom+"' AND '"+dtTo+"'\r\nAND LS.STOCKTRANSTYPE = 'BPROD INPUT'\r\nGROUP BY TL.LOCATIONTYPE , LS.DOCDATE\r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY , 0 RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY , 0 IPYQTY,0 IPAQTY, 0 STKPQTY,SUM(MINUSQTY) STKMQTY, \r\n0 FDRM,0 ITEMQTY,0 PACK,0 DRUM,0 STR,0\r\nFROM LSTOCKVALUE LS , LOCDETAILS TL , ITEMMASTER I\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND (TL.LOCID IN ( 'CURING' , 'RVD SHED' ) OR TL.LOCATIONTYPE IN ( 'POLISH','PACKING') )\r\nAND I.SNCATEGORY IN ('POLISH POWDER')\r\nAND LS.DRUMNO IS NOT NULL\r\nAND LS.DOCDATE BETWEEN  '"+dtFrom+"' AND  '"+dtTo+"'\r\nAND UPPER(LS.STOCKTRANSTYPE) in  ('STOCK RECONCILATION','STOCK VARIATION','FIRE DRUMS','DIRECT DEDUCTION','DRUM STK RECL')\r\nGROUP BY TL.LOCATIONTYPE,LS.DOCDATE\r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY , 0 RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY ,0 IPYQTY, SUM(LS.PLUSQTY) IPAQTY,0 STKPQTY,0 STKMQTY, \r\n0 FDRM,0 ITEMQTY,0 PACK,0 DRUM,0 STR,0\r\nFROM LSTOCKVALUE LS , ITEMMASTER I , LOCDETAILS TL , LOCDETAILS FL\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND I.SNCATEGORY IN ('POLISH POWDER')\r\nAND TL.LOCATIONTYPE='PASTE'\r\nAND LS.FROMLOCID = FL.LOCDETAILSID\r\nAND FL.LOCATIONTYPE IN ('CURING','POLISH','PACKING')\r\nAND LS.DOCDATE BETWEEN '"+dtFrom+"' AND '"+dtTo+"'\r\nAND LS.STOCKTRANSTYPE IN ('CURING RECHARGE','DRUM ISSUE')\r\nGROUP BY TL.LOCID , FL.LOCID , LS.DOCDATE\r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY , 0 RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY , 0 IPYQTY,0 IPAQTY, 0 STKPQTY,0 STKMQTY,0 FDRM,\r\nSUM(LS.PLUSQTY) ITEMQTY,0 PACK,0 DRUM,0 STR,0\r\nFROM LSTOCKVALUE LS , LOCDETAILS TL , ITEMMASTER I, ICEDETAIL ICD, ICEBASIC ICB, ITEMMASTER FI\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND ICB.ICEBASICID = ICD.ICEBASICID\r\nAND ICD.ICEDETAILID = LS.T1SOURCEID\r\nAND ICB.FITEMID = FI.ITEMMASTERID\r\nAND FI.SNCATEGORY <> I.SNCATEGORY\r\nAND (TL.LOCID IN ( 'CURING' , 'RVD SHED' ) OR TL.LOCATIONTYPE IN ( 'POLISH','PACKING') )\r\nAND I.SNCATEGORY = 'POLISH POWDER'\r\nAND LS.DOCDATE BETWEEN '"+dtFrom+"' AND '"+dtTo+"'\r\nAND LS.STOCKTRANSTYPE = 'ITEM CONV' \r\nGROUP BY LS.DOCDATE , TL.LOCID\r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY , 0 RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY , 0 IPYQTY,0 IPAQTY, 0 STKPQTY,0 STKMQTY,0 FDRM,\r\n0  ITEMQTY,0 PACK,0 DRUM,0 STR, SUM(LS.MINUSQTY) ITEMCQTY\r\nFROM LSTOCKVALUE LS , LOCDETAILS TL , ITEMMASTER I, ICEDETAIL ICD, ICEBASIC ICB, ITEMMASTER FI\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND ICB.ICEBASICID = ICD.ICEBASICID\r\nAND ICD.ICEDETAILID = LS.T1SOURCEID\r\nAND ICB.TITEMID = FI.ITEMMASTERID\r\nAND FI.SNCATEGORY <> I.SNCATEGORY\r\nAND (TL.LOCID IN ( 'CURING' , 'RVD SHED' ) OR TL.LOCATIONTYPE IN ( 'POLISH','PACKING') )\r\nAND I.SNCATEGORY = 'POLISH POWDER'\r\nAND LS.DOCDATE BETWEEN '"+dtFrom+"' AND '"+dtTo+"'\r\nAND LS.STOCKTRANSTYPE = 'ITEM CONV' \r\nGROUP BY LS.DOCDATE , TL.LOCID\r\nUNION ALL\r\nSELECT LS.DOCDATE , 0 OPQTY , 0 RQTY , 0 IPKQTY , 0 IMPKQTY,0 IPOQTY ,0 IPYQTY, 0 IPAQTY,0 STKPQTY,0 STKMQTY, \r\n0 FDRM,0 ITEMQTY,0 PACK,0 DRUM,SUM(LS.PLUSQTY) StR,0\r\nFROM LSTOCKVALUE LS , ITEMMASTER I , LOCDETAILS TL , LOCDETAILS FL\r\nWHERE LS.ITEMID = I.ITEMMASTERID\r\nAND LS.LOCID = TL.LOCDETAILSID\r\nAND I.SNCATEGORY IN ('POLISH POWDER')\r\nAND TL.LOCATIONTYPE='PACKING'\r\nAND LS.FROMLOCID = FL.LOCDETAILSID\r\nAND FL.LOCATIONTYPE IN ('STORES')\r\nAND LS.DOCDATE BETWEEN '"+dtFrom+"' AND '"+dtTo+"'\r\nGROUP BY TL.LOCID , FL.LOCID , LS.DOCDATE";

            OracleDataAdapter adapter = new OracleDataAdapter(SvSql, _connectionString);
            using (DataTable dtReport = new DataTable())
            {
                adapter.Fill(dtReport);

                DataView dv1 = dtReport.DefaultView;
                // dv1.RowFilter = " TotalOutstandingAmount > 0 AND  OutstandingPrinciple > 0  ";

                dtNew1 = dv1.ToTable();
                using (XLWorkbook wb = new XLWorkbook())
                {
                    wb.Worksheets.Add(dtNew1, "CuringShedStockPolishDetails");


                    using (MemoryStream MyMemoryStream = new MemoryStream())
                    {
                        Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                        Response.Headers.Add("content-disposition", "attachment;  filename=CuringShedStockPolishDetails.xlsx");
                        wb.SaveAs(MyMemoryStream);
                        //MyMemoryStream.WriteTo(Response.OutputStream);
                        //Response.Flush();
                        //Response.End();
                        //wb.SaveAs(MyMemoryStream);
                        return File(MyMemoryStream.ToArray(), "application/ms-excel", "CuringShedStockPolishDetails.xlsx");
                    }
                }

            }

        }
    }
}
